spring.application.name: api-gateway
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: product-catalog-service              
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/products/**
    refresh:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:      
      redisratelimiter: DEBUG
      springframework: 
        web: TRACE       
        cloud:
          gateway: TRACE
          loadbalancer: TRACE
